location: .gitman
sources:
- name: mrs_gazebo_common_resources
  type: git
  repo: git@github.com:ctu-mrs/mrs_gazebo_common_resources.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_gazebo_common_resources
  scripts:
  - git submodule update --init --recursive --depth 1
- name: mrs_simulation
  type: git
  repo: git@github.com:ctu-mrs/mrs_simulation.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_simulation
  scripts:
  - git submodule update --init --recursive --depth 1
- name: px4
  type: git
  repo: git@github.com:ctu-mrs/px4_firmware.git
  sparse_paths:
  -
  rev: v1.10.1
  link: ros_packages/px4
  scripts:
  - git submodule update --init --recursive --depth 1
sources_locked:
- name: mrs_simulation
  type: git
  repo: git@github.com:ctu-mrs/mrs_simulation.git
  sparse_paths:
  -
  rev: 0dd7a85163407c3d4a41ef9129194d807fb4a359
  link: ros_packages/mrs_simulation
  scripts:
  - git submodule update --init --recursive --depth 1
- name: px4
  type: git
  repo: git@github.com:ctu-mrs/px4_firmware.git
  sparse_paths:
  -
  rev: d5673c5fa7afbda2ef7af4db451a0fc0cc52f1f3
  link: ros_packages/px4
  scripts:
  - git submodule update --init --recursive --depth 1
