location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/mrs_gazebo_common_resources.git
    name: mrs_gazebo_common_resources
    rev: master
    type: git
    sparse_paths:
      -
    link:
    links:
      - source: ''
        target: ros_packages/mrs_gazebo_common_resources
    scripts:
      - git submodule update --init --recursive --depth 1
  - repo: https://github.com/ctu-mrs/mrs_simulation.git
    name: mrs_simulation
    rev: master
    type: git
    sparse_paths:
      -
    link:
    links:
      - source: ''
        target: ros_packages/mrs_simulation
    scripts:
      - git submodule update --init --recursive --depth 1
  - repo: https://github.com/ctu-mrs/px4_firmware.git
    name: px4_firmware
    rev: 1.13.1
    type: git
    sparse_paths:
      -
    link:
    links:
      - source: ''
        target: ros_packages/px4_firmware
    scripts:
      - git submodule update --init --recursive --depth 1
  - repo: https://github.com/ctu-mrs/px4_sitl_gazebo.git
    name: mavlink_sitl_gazebo
    rev: bd941689b6e9d3e628a1e786d1d042d48005dc7b
    type: git
    sparse_paths:
      -
    link:
    links:
      - source: ''
        target: ros_packages/mavlink_sitl_gazebo
    scripts:
      - git submodule update --init --recursive --depth 1
sources_locked:
  - repo: https://github.com/ctu-mrs/mrs_gazebo_common_resources.git
    name: mrs_gazebo_common_resources
    rev: 08b29b4f767dec97220d7a1e4ad32ad7e50c4dca
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive --depth 1
  - repo: https://github.com/ctu-mrs/mrs_simulation.git
    name: mrs_simulation
    rev: 9a9d94232fc3a7ab7a1f6c41872ccfe67c4b1b0e
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive --depth 1
  - repo: https://github.com/ctu-mrs/px4_firmware.git
    name: px4_firmware
    rev: 18e2109234f7243c19a4a7d2c410dc232d7f80f9
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive --depth 1
  - repo: https://github.com/ctu-mrs/px4_sitl_gazebo.git
    name: mavlink_sitl_gazebo
    rev: 017dad4db7824b947ed4ff88a0bef37c132fd433
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive --depth 1
default_group: ''
groups:
  -
