location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/mrs_gazebo_common_resources.git
    name: mrs_gazebo_common_resources
    rev: master
    type: git
    sparse_paths:
      -
    link:
    links:
      - source: ''
        target: ros_packages/mrs_gazebo_common_resources
    scripts:
      - git submodule update --init --recursive --depth 1
  - repo: https://github.com/ctu-mrs/mrs_simulation.git
    name: mrs_simulation
    rev: master
    type: git
    sparse_paths:
      -
    link:
    links:
      - source: ''
        target: ros_packages/mrs_simulation
    scripts:
      - git submodule update --init --recursive --depth 1
  - repo: https://github.com/ctu-mrs/px4_firmware.git
    name: px4_firmware
    rev: 1.13.1
    type: git
    sparse_paths:
      -
    link:
    links:
      - source: ''
        target: ros_packages/px4_firmware
    scripts:
      - git submodule update --init --recursive --depth 1
  - repo: https://github.com/ctu-mrs/px4_sitl_gazebo.git
    name: mavlink_sitl_gazebo
    rev: bd941689b6e9d3e628a1e786d1d042d48005dc7b
    type: git
    sparse_paths:
      -
    link:
    links:
      - source: ''
        target: ros_packages/mavlink_sitl_gazebo
    scripts:
      - git submodule update --init --recursive --depth 1
sources_locked:
  - repo: https://github.com/ctu-mrs/mrs_gazebo_common_resources.git
    name: mrs_gazebo_common_resources
    rev: 08b29b4f767dec97220d7a1e4ad32ad7e50c4dca
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive --depth 1
  - repo: https://github.com/ctu-mrs/mrs_simulation.git
    name: mrs_simulation
    rev: 8d9c64d5f3de4b24f71d004bc588b4e974aeb0ec
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive --depth 1
  - repo: https://github.com/ctu-mrs/px4_firmware.git
    name: px4_firmware
    rev: 7eff914511d9e64b9039d481a52f05f38f367424
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive --depth 1
  - repo: https://github.com/ctu-mrs/px4_sitl_gazebo.git
    name: mavlink_sitl_gazebo
    rev: 56b5508b72f40339448f3525dd4dc51f30512cbd
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive --depth 1
default_group: ''
groups:
  -
