location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/mrs_gazebo_common_resources.git
    name: mrs_gazebo_common_resources
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_gazebo_common_resources
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_simulation.git
    name: mrs_simulation
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_simulation
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/px4_firmware.git
    name: px4_firmware
    rev: 1.13.2
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/px4_firmware
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/px4_sitl_gazebo.git
    name: mavlink_sitl_gazebo
    rev: firmware_1.13.2
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mavlink_sitl_gazebo
    scripts:
      - git submodule update --init --recursive
sources_locked:
  - repo: https://github.com/ctu-mrs/mrs_gazebo_common_resources.git
    name: mrs_gazebo_common_resources
    rev: 13c56ea9c98f8590ebc5aee7d13a0e9ab8d7d26f
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_gazebo_common_resources
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_simulation.git
    name: mrs_simulation
    rev: 2379f1cfb826bfab5f7be04fad1e844e89c7da37
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_simulation
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/px4_firmware.git
    name: px4_firmware
    rev: 531b63a2935ca6130a2ab52c835faddb010e46b2
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/px4_firmware
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/px4_sitl_gazebo.git
    name: mavlink_sitl_gazebo
    rev: e541acf81ce625415c98a54261052e13462a61a3
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mavlink_sitl_gazebo
    scripts:
      - git submodule update --init --recursive
default_group: ''
groups:
  -
