location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/mrs_gazebo_common_resources.git
    name: mrs_gazebo_common_resources
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_gazebo_common_resources
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_simulation.git
    name: mrs_simulation
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_simulation
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/px4_firmware.git
    name: px4_firmware
    rev: 1.13.2
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/px4_firmware
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/px4_sitl_gazebo.git
    name: mavlink_sitl_gazebo
    rev: bd941689b6e9d3e628a1e786d1d042d48005dc7b
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mavlink_sitl_gazebo
    scripts:
      - git submodule update --init --recursive
sources_locked:
  - repo: https://github.com/ctu-mrs/mrs_gazebo_common_resources.git
    name: mrs_gazebo_common_resources
    rev: 13c56ea9c98f8590ebc5aee7d13a0e9ab8d7d26f
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_gazebo_common_resources
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_simulation.git
    name: mrs_simulation
    rev: 6d91661f7b0ec9b93cf0c4c9a4a6f181f70cb442
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_simulation
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/px4_firmware.git
    name: px4_firmware
    rev: 531b63a2935ca6130a2ab52c835faddb010e46b2
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/px4_firmware
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/px4_sitl_gazebo.git
    name: mavlink_sitl_gazebo
    rev: bd941689b6e9d3e628a1e786d1d042d48005dc7b
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mavlink_sitl_gazebo
    scripts:
      - git submodule update --init --recursive
default_group: ''
groups:
  -
