location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/mrs_gazebo_common_resources.git
    name: mrs_gazebo_common_resources
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_gazebo_common_resources
    scripts:
      - git submodule update --init --recursive --depth 1
  - repo: https://github.com/ctu-mrs/mrs_simulation.git
    name: mrs_simulation
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_simulation
    scripts:
      - git submodule update --init --recursive --depth 1
  - repo: https://github.com/ctu-mrs/px4_firmware.git
    name: px4_firmware
    rev: 1.11.2
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/px4_firmware
    scripts:
      - git submodule update --init --recursive --depth 1
sources_locked:
  - repo: https://github.com/ctu-mrs/mrs_gazebo_common_resources.git
    name: mrs_gazebo_common_resources
    rev: 08b29b4f767dec97220d7a1e4ad32ad7e50c4dca
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_gazebo_common_resources
    scripts:
      - git submodule update --init --recursive --depth 1
  - repo: https://github.com/ctu-mrs/mrs_simulation.git
    name: mrs_simulation
    rev: 3aaccc081e963d39e733bb47a38f7ca7a59536e9
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_simulation
    scripts:
      - git submodule update --init --recursive --depth 1
  - repo: https://github.com/ctu-mrs/px4_firmware.git
    name: px4_firmware
    rev: 1ee88accfe526d0c07f4e0b62bff0e81243add07
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/px4_firmware
    scripts:
      - git submodule update --init --recursive --depth 1
default_group: ''
groups:
  -
